basePath: /api/v1
definitions:
  attendances.Attendance:
    properties:
      attendedAt:
        type: string
      classId:
        type: integer
      createdAt:
        type: string
      id:
        type: integer
      isAttended:
        type: boolean
      studentId:
        type: integer
      updatedAt:
        type: string
    type: object
  attendances.CreateAttendanceRequest:
    properties:
      attendedAt:
        type: string
      classId:
        type: integer
      isAttended:
        type: boolean
      studentId:
        type: integer
    type: object
  attendances.UpdateAttendanceRequest:
    properties:
      id:
        type: integer
      isAttended:
        type: boolean
    type: object
  registrations.FindRegistrationResp:
    properties:
      data:
        items:
          $ref: '#/definitions/registrations.Registration'
        type: array
      page:
        type: integer
    type: object
  registrations.Registration:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      isProcessed:
        type: boolean
      note:
        type: string
      parentName:
        type: string
      phoneNumber:
        type: string
      studentClass:
        description: |-
          Class type:
          * buds - Children who is 3 yo.
          * seed - Children who is 4 yo.
          * leaf - Children who is 5 yo.
        enum:
        - buds
        - seed
        - leaf
        type: string
      studentDob:
        type: string
      studentName:
        type: string
      updatedAt:
        type: string
    type: object
  registrations.WriteRegistrationRequest:
    properties:
      note:
        type: string
      parentName:
        type: string
      phoneNumber:
        type: string
      studentClass:
        description: |-
          Class type:
          * buds - Children who is 3 yo.
          * seed - Children who is 4 yo.
          * leaf - Children who is 5 yo.
        enum:
        - buds
        - seed
        - leaf
        type: string
      studentDob:
        type: string
      studentName:
        type: string
    type: object
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is a sample swagger for Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Fiber Example API
  version: "1.0"
paths:
  /attendances:
    get:
      consumes:
      - application/json
      description: Get list attendance
      parameters:
      - description: Page
        in: query
        name: page
        type: integer
      - description: Page Size
        in: query
        name: pageSize
        type: integer
      - default: desc
        description: Sort direction
        enum:
        - asc
        - desc
        in: query
        name: sort
        type: string
      - description: Class id
        in: query
        name: classId
        required: true
        type: string
      - description: Time range
        in: query
        name: period
        type: string
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              items:
                $ref: '#/definitions/attendances.Attendance'
              type: array
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Get list attendance details api
      tags:
      - Attendance
    patch:
      consumes:
      - application/json
      description: Patch attendance
      parameters:
      - description: Patch attendance body
        in: body
        name: post
        required: true
        schema:
          items:
            $ref: '#/definitions/attendances.UpdateAttendanceRequest'
          type: array
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/attendances.Attendance'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Patch attendance api
      tags:
      - Attendance
    post:
      consumes:
      - application/json
      description: Insert attendance
      parameters:
      - description: Create attendance body
        in: body
        name: post
        required: true
        schema:
          items:
            $ref: '#/definitions/attendances.CreateAttendanceRequest'
          type: array
      responses:
        "200":
          description: OK
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Create attendance api
      tags:
      - Attendance
  /registrations:
    delete:
      consumes:
      - application/json
      description: Delete registration
      parameters:
      - description: Registration IDs
        in: query
        items:
          type: integer
        name: ids
        required: true
        type: array
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Delete registration api
      tags:
      - Registration
    get:
      consumes:
      - application/json
      description: Get list registration
      parameters:
      - description: Page
        in: query
        name: page
        type: integer
      - description: Page Size
        in: query
        name: pageSize
        type: integer
      - default: desc
        description: Sort direction
        enum:
        - asc
        - desc
        in: query
        name: sort
        type: string
      - description: Search term
        in: query
        name: search
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/registrations.FindRegistrationResp'
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Get list registration details api
      tags:
      - Registration
    post:
      consumes:
      - application/json
      description: Insert registration
      parameters:
      - description: Create registration body
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/registrations.WriteRegistrationRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/registrations.Registration'
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Create registration api
      tags:
      - Registration
  /registrations/{id}:
    get:
      consumes:
      - application/json
      description: Get one registration
      parameters:
      - description: Registration ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/registrations.Registration'
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Get registration details api
      tags:
      - Registration
    patch:
      consumes:
      - application/json
      description: Mark a registration as processed
      parameters:
      - description: Registration ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Mark as done registration api
      tags:
      - Registration
    put:
      consumes:
      - application/json
      description: Update registration
      parameters:
      - description: Update registration body
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/registrations.WriteRegistrationRequest'
      - description: Registration ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/registrations.Registration'
        "500":
          description: Internal Server Error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Update registration api
      tags:
      - Registration
securityDefinitions:
  ApiKeyAuth:
    description: Apply "bearer " before token in authorization
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
