import { z } from 'zod'

export const CreateStudentSchema = z.object({
    firstName: z.string().nonempty({ message: 'Tên bé không được bỏ trống' }),
    lastName: z.string().nonempty({ message: 'Họ và tên lót bé không được bỏ trống' }),
    grade: z.string().nonempty({ message: 'Khối lớp không được bỏ trống' }),
    enrollDate: z.string(),
    dob: z.string(),
    birthYear: z.string(),
    gender: z.string(),
    ethnic: z.string(),
    birthPlace: z.string(),
    tempRes: z.string(),
    permResProvince: z.string(),
    permResDistrict: z.string(),
    permResCommune: z.string(),
    agencyId: z.number().int().positive({ message: 'Trường học không được bỏ trống' }),
    classRoomId: z.number().optional(),
    parentName: z.string().nonempty({ message: 'Tên phụ huynh không được bỏ trống' }),
    studentId: z.number().optional(),
    parentDob: z.string(),
    parentGender: z.string().nonempty({ message: 'Giới tính không bỏ trống' }),
    parentPhoneNumber: z.string(),
    parentZalo: z.string(),
    parentOccupation: z.string(),
    parentLandlord: z.string(),
    parentRoi: z.string(),
    parentBirthPlace: z.string(),
    parentResRegistration: z.string(),
})
